FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libncurses5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libgdbm-dev \
    libdb5.3-dev \
    libbz2-dev \
    libexpat1-dev \
    liblzma-dev \
    libffi-dev \
    wget \
    curl \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz -o python.tgz \
    && tar xzf python.tgz \
    && cd Python-3.10.0 \
    && ./configure --enable-optimizations \
    && make -j8 \
    && make altinstall \
    && rm -rf /Python-3.10.0

# Set pip and python to default to version 3.10
RUN ln -s /usr/local/bin/pip3.10 /usr/local/bin/pip \
    && ln -s /usr/local/bin/python3.10 /usr/local/bin/python
