name: 🧩 Feature request
description: Suggest an idea or a feature.
labels: ["feature request"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your idea.

  - type: textarea

  - type: textarea
    id: description
    attributes:
      label: Describe the problem you'd like to have solved
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: ideal-solution
    attributes:
      label: Describe the ideal solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives-and-workarounds
    attributes:
      label: Alternatives and current workarounds
      description: A clear and concise description of any alternatives you've considered or any workarounds that are currently in place.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false